image: Ubuntu2204

install:
  - sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libgif-dev libwebp-dev libavif-dev -y
  - git clone --depth=1 --branch=avif_cmake https://github.com/sturkmen72/opencv.git
  - git clone --depth=1 --branch=4.x https://github.com/sturkmen72/opencv_extra.git
  - export OPENCV_TEST_DATA_PATH=$(pwd)/opencv_extra/testdata
  - mkdir build-opencv
  - cd build-opencv
  - cmake -DBUILD_PERF_TESTS=OFF -DWITH_ZLIB_NG=OFF -DWITH_IMGCODEC_GIF=ON -DWITH_SPNG=OFF -DWITH_JPEG=ON -DWITH_TIFF=OFF -DWITH_JASPER=OFF -DWITH_OPENEXR=OFF -DWITH_IPP=OFF -DWITH_ADE=OFF -DWITH_ITT=OFF -DBUILD_OPENJPEG=OFF -DBUILD_PROTOBUF=OFF -DBUILD_JAVA=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_gapi=OFF -DBUILD_opencv_features2d=OFF -DBUILD_opencv_flann=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_ml=OFF -DBUILD_opencv_objdetect=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_stitching=OFF -DCMAKE_BUILD_TYPE=Release ../opencv
  - make
  - ./bin/opencv_test_imgcodecs
  - cd ..

build_script:
  - mkdir build
  - cd build
  - cmake -DOpenCV_DIR=/home/appveyor/projects/opencv-image-reading/build-opencv ..
  - make
  - ./test-1
  - ./test-2

artifacts:
  - path: /home/appveyor/projects/opencv-image-reading/build-opencv/bin/PNG_SAVED_DEFAULT.png
    name: PNG_SAVED_DEFAULT.png
