version: 1.0.{build}
image: macOS-Catalina

environment:
  arch: ARM

install:
  - uname -a
  - uname -p
  - git clone --branch=libjpegturbo_nasm https://github.com/ocpalo/opencv.git
  - git clone --depth=1 https://github.com/opencv/opencv_extra.git
  - brew install nasm
  - mkdir build-opencv
  - cd build-opencv
  - cmake -DWITH_LIBJPEG_TURBO_SIMD=ON -DWITH_JASPER=OFF -DWITH_WEBP=OFF -DWITH_OPENEXR=OFF -DWITH_IPP=OFF -DWITH_ADE=OFF -DWITH_ITT=OFF -DBUILD_IPP_IW=OFF -DBUILD_ITT=OFF -DBUILD_OPENEXR=OFF -DBUILD_OPENJPEG=OFF -DBUILD_PROTOBUF=OFF -DBUILD_WEBP=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_JAVA=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_gapi=OFF -DBUILD_opencv_features2d=ON -DBUILD_opencv_flann=ON -DBUILD_opencv_video=ON -DBUILD_opencv_ml=ON -DBUILD_opencv_objdetect=ON -DBUILD_opencv_photo=OFF -DBUILD_opencv_calib3d=ON -DBUILD_opencv_stitching=OFF -DCMAKE_BUILD_TYPE=Release ../opencv
  - make -j8
  - cd ..
  - export OPENCV_TEST_DATA_PATH="$PWD/opencv_extra/testdata"
  - export JSIMD_NOHUFFENC=1
  - cd build-opencv/bin/
  - ./opencv_test_objdetect
  - ./opencv_test_videoio
  - echo "test"
