version: 1.0.{build}
image: Visual Studio 2017

platform:
  - x64

install:
  - cmd: echo "compile OpenCV"
  - cmd: cd NASM
  - cmd: 7z e NASM.zip
  - cmd: set PATH=%PATH%;C:\projects\opencv-image-reading\NASM
  - cmd: cd ..
  - cmd: nasm -v
  - cmd: git clone --branch=libjpegturbo_nasm https://github.com/ocpalo/opencv.git
  - cmd: git clone --depth=1 https://github.com/opencv/opencv_extra.git
  - cmd: md build-opencv
  - cmd: cd build-opencv
  - cmd: cmake -DWITH_LIBJPEG_TURBO_SIMD=ON -DWITH_JASPER=OFF -DWITH_WEBP=OFF -DWITH_OPENEXR=OFF -DWITH_IPP=OFF -DWITH_ADE=OFF -DWITH_ITT=OFF -DBUILD_IPP_IW=OFF -DBUILD_ITT=OFF -DBUILD_OPENEXR=OFF -DBUILD_OPENJPEG=OFF -DBUILD_PROTOBUF=OFF -DBUILD_WEBP=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_JAVA=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_gapi=OFF -DBUILD_opencv_features2d=OFF -DBUILD_opencv_flann=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_ml=OFF -DBUILD_opencv_objdetect=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_stitching=OFF ../opencv -G "Visual Studio 15 2017 Win64"
  - cmd: cmake --build . --config Release
  - cmd: cd..
  - cmd: set PATH=%PATH%;C:\projects\opencv-image-reading\build-opencv\bin\Release
  - cmd: set OpenCV_DIR=C:\projects\opencv-image-reading\build-opencv
  - cmd: set OPENCV_TEST_DATA_PATH=C:\projects\opencv-image-reading\opencv_extra\testdata
  - cmd: C:\projects\opencv-image-reading\build-opencv\bin\Release\opencv_test_imgcodecs.exe
  - cmd: md build
  - cmd: cd build
  - cmd: cmake .. -G "Visual Studio 15 2017 Win64"
  - cmd: cmake --build . --config Release
  - cmd: cd..
  - cmd: C:\projects\opencv-image-reading\build\Release\test-1.exe
  - cmd: C:\projects\opencv-image-reading\build\Release\test-1.exe
  - cmd: C:\projects\opencv-image-reading\build\Release\test-2.exe
  - cmd: C:\projects\opencv-image-reading\build\Release\test-2.exe
  - cmd: cd opencv
  - cmd: git reset --hard 734190964a310ca361a9ba721e4b27bab2cf6302
  - cmd: cd..
  - cmd: cd build-opencv
  - cmd: cmake --build . --config Release
  - cmd: cd..
  - cmd: C:\projects\opencv-image-reading\build\Release\test-1.exe
  - cmd: C:\projects\opencv-image-reading\build\Release\test-1.exe
  - cmd: C:\projects\opencv-image-reading\build\Release\test-2.exe
  - cmd: C:\projects\opencv-image-reading\build\Release\test-2.exe

build_script:
  - cmd: cd build
  - cmd: cmake .. -G "Visual Studio 15 2017 Win64"
  - cmd: cmake --build . --config Release

test_script:
  - cmd: C:\projects\opencv-image-reading\build-opencv\bin\Release\opencv_test_imgcodecs.exe
  - cmd: C:\projects\opencv-image-reading\build-opencv\bin\Release\opencv_test_imgcodecs.exe

