version: 1.0.{build}
image: Visual Studio 2019

platform:
  - x64

install:
  - cmd: echo "compile OpenCV with NASM to enable inline assembly code"
  - cmd: pip install numpy
  - cmd: cd NASM
  - cmd: 7z e NASM.zip
  - cmd: set PATH=%PATH%;C:\projects\opencv-image-reading\NASM
  - cmd: cd ..
  - cmd: nasm -v
  - cmd: git clone --branch=test_nasm https://github.com/ocpalo/opencv.git
  - cmd: git clone --depth=1 https://github.com/opencv/opencv_extra.git
  - cmd: md build-opencv
  - cmd: cd build-opencv
  - cmd: cmake -DWITH_JASPER=OFF -DWITH_WEBP=OFF -DWITH_OPENEXR=OFF -DBUILD_PROTOBUF=OFF -DBUILD_WEBP=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_JAVA=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_gapi=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_stitching=OFF ../opencv -G "Visual Studio 16 2019" 
  - cmd: cmake --build . --config Release
  - cmd: cd..
  - cmd: set OPENCV_LOG_LEVEL=DEBUG
  - cmd: set PATH=%PATH%;C:\projects\opencv-image-reading\build-opencv\bin\Release
  - cmd: set OpenCV_DIR=C:\projects\opencv-image-reading\build-opencv
  - cmd: set OPENCV_TEST_DATA_PATH=C:\projects\opencv-image-reading\opencv_extra\testdata
  - cmd: C:\projects\opencv-image-reading\build-opencv\bin\Release\opencv_test_imgcodecs.exe
  - cmd: C:\projects\opencv-image-reading\build-opencv\bin\Release\opencv_test_objdetect.exe
  - cmd: C:\projects\opencv-image-reading\build-opencv\bin\Release\opencv_test_videoio.exe
